name: Deploy to GCP Cloud Run

on:
  push:
    branches:
      - main-gcp

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME : production-glitch-react
      PROJECT_ID : invirtu
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        project_id: invirtu
        service_account_key: ${{ secrets.GCP_GLITCH }}
        export_default_credentials: true

    - name: Get secrets from Secret Manager
      uses: google-github-actions/get-secretmanager-secrets@v1
      id: secrets
      with:
        project_id: invirtu
        secrets: |-
          token:projects/522989861526/secrets/glitch-production-react-env

    - name: Create .env file
      run: |
        echo "${{ steps.secrets.outputs.token}}" >> .env


    - name: Build Docker image
      run: docker build -t gcr.io/invirtu/production-glitch-react -f .docker/production/Dockerfile . 

    - name: Push Docker image to Google Cloud Storage
      env:
        GIT_TAG: v0.1.0
      run: |
        gcloud auth configure-docker -q
        docker tag gcr.io/invirtu/${{ env.IMAGE_NAME }}:latest gcr.io/invirtu/${{ env.IMAGE_NAME }}:latest
        docker tag gcr.io/invirtu/${{ env.IMAGE_NAME }}:latest gcr.io/invirtu/${{ env.IMAGE_NAME }}:${{ github.sha }}
        docker push gcr.io/invirtu/${{ env.IMAGE_NAME }}:latest
        docker push gcr.io/invirtu/${{ env.IMAGE_NAME }}:${{ github.sha }}
        
         

    - name: Deploy to Cloud Run
      uses: google-github-actions/deploy-cloudrun@v1
      with:
          image: gcr.io/invirtu/production-glitch-react:${{ github.sha }}
          project_id: invirtu
          region: us-central1
          service: production-glitch-react
          platform: managed
          env_vars_file: .env
          allow_unauthenticated: true
          port: 80
          min_instances: 1
          args:
            -- 'port=80'
            -- 'min-instances=1'
          traffic_percent_strategy: '{"latest":50}'
    

   
        

