name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: invirtu
      APP_NAME: glitch-production
      GAE_SERVICE: default
      GAE_VERSION: v1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_GLITCH }}
          export_default_credentials: true

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Build and Test
        run: |
          npm ci
          npm run build

      - name: Deploy to App Engine
        run: |
          gcloud app deploy --project ${{ env.PROJECT_ID }} --quiet --version ${{ env.GAE_VERSION }} --no-promote --stop-previous-version